bocpay:
    location: config/conf-bocpay.json
    gateway: https://api.pay.dcorepay.com
#    gateway: https://2api.cib.dcorepay.com
    charset: UTF-8

alipay:
    location: config/conf-alipay.json
    origin: http://slee.hz2sl.com
#    origin: http://dev.becypress.com
    gateway: https://openapi.alipay.com/gateway.do
#    gateway: https://openapi.alipaydev.com/gateway.do
    oauth: https://openauth.alipay.com/oauth2/publicAppAuthorize.htm
#    oauth: https://openauth.alipaydev.com/oauth2/publicAppAuthorize.htm
    charset: UTF-8
    format: json
    sign-type: RSA2
#    sign-type: RSA

wechat:
    location: config/conf-wechat.json
    origin: http://dev.becypress.com
    oauth: https://open.weixin.qq.com/connect/oauth2/authorize
    charset: UTF-8

ftp:
    location: config/conf-ftp.json
    charset: UTF-8